# Leave this out if using subdirectories in path. It causes issues with toCSS.
# baseURL: 'http://example.org/'
relativeURLs: true
languageCode: en
title: Maleah Cain Resume
theme: hugo-devresume-theme
params:
  author: CowboySmall
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  primaryColor: '#54B689'
  textPrimaryColor: '#292929'
  profile:
    enable: true
    name: Maleah Cain
    tagline: Software Engineer
    avatar: avatar.jpg
  contact:
    enable: true
    location: Alabama
    list:
      # - icon: fas fa-phone-square
        # url: 'tel:#'
        # text: 0123 4567 87
      - icon: fas fa-envelope-square
        url: 'mailto:#'
        text: maleahcain@yahoo.com
      - icon: fas fa-globe
        url: '#'
        text: 
  skills:
    enable: true
    list:
      - title: Technical
        items:
          - details: Programming in C++
          - details: Linux
          - details: Cybersecurity
          - details: Web Development
          - details: Computer Software
          - details: Computer Hardware
      - title: Professional
        items:
          - details: Efficient
          - details: Problem Solver
          - details: Detail-oriented
          - details: Analytical Thinker
  education:
    enable: true
    list:
      - degree: AAS in Computer Information Systems
        university: Northeast Alabama Community College
        dates: 2018 - 2020
  awards:
    enable: true
    list:
      - name: IC3 Digital Literacy
        body: Northeast Alabama Community College
        date: '2018'
  languages:
    enable: false
    list:
      - name: English
        level: Native
      - name: Spanish
        level: Professional
  interests:
    enable: true
    list:
      - name: Music
      - name: Video Games
      - name: Basketball
      - name: Design
      - name: Art
  summary:
    enable: true
    text: >-
      Hi, my name is Maleah Cain. Currently, I am working towards my 
      Associate of Applied Science Degree in Computer Information Systems.
      This fall, I plan to graduate and earn my degree. Since I am near graduating,
      I am ready to enter the workforce using my skills and experiences gained from my classes.
  experience:
    enable: true
    list:
      - title: English Teacher Aide
        dates: 2017 - 2018
        company: Skyline Highschool
        details: >-
          Aided an english teacher in multiple tasks.
        items:
          - details: 'Graded and organized student papers'
          - details: Distributed school books.
          - details: Printed school papers.
      - title: Office Aide
        dates: 2017 - 2018
        company: Skyline Highschool
        details: >-
          Assisted highschool office in clerical tasks
        items:
          - details: 'Answered phone calls'
          - details: Delivered papers and documents.
  projects:
    enable: false
    list:
      - title: Project Lorem Ipsum
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Lorem ipsum dolor sit
          amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          Aenean massa. Cum sociis natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus.
      - title: Project Sed Fringilla
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
      - title: Project Praesent
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
  information:
    enable: false
    list:
      - title: Papers
        items:
          - details: 2018 · Lorem Ipsum
          - details: 2016 · Sed Fringilla
      - title: Interests
        details: 'Climbing, Snowboarding, Photography, Travelling'
  social:
    enable: true
    list:
      - icon: fab fa-github-square
        url: //github.com/username
        title: MaleahJay
      # - icon: fab fa-linkedin
        # url: //linkedin.com/in/username
        # title: username
      # - icon: fab fa-twitter-square
        # url: //twitter.com/username
        # title: '@username'
  footer:
    copyright: Maleah Cain
